# Generated by Django 3.2.9 on 2022-11-08 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.TextField(db_index=True, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('problem_id', models.IntegerField()),
                ('contest_id', models.IntegerField()),
                ('content', utils.models.RichTextField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('submission_id', models.IntegerField()),
                ('answer_registered', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
