# Generated by Django 3.2.9 on 2022-11-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='contest_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_by',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(default='None'),
        ),
    ]
