# Generated by Django 3.2.9 on 2022-11-14 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0003_auto_20221114_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=utils.models.RichTextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='contest_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='problem_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='submission_id',
            field=models.IntegerField(),
        ),
    ]
