# Generated by Django 3.2.9 on 2022-11-11 07:51

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.TextField(db_index=True, primary_key=True, serialize=False)),
                ('created_by', models.IntegerField()),
                ('content', utils.models.RichTextField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('submission_id', models.IntegerField()),
                ('question_id', models.IntegerField(null=True)),
            ],
        ),
    ]
